services:
  donetick:
    image: donetick/donetick:latest
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/app/data/donetick.db
      
